[workspace]
name = "Name of your project"
version = "0.1.0"
authors = ["Your name and email"]
channels = ["conda-forge", "pytorch", "anaconda"]
platforms = ["linux-64"]

[dependencies]
python = "3.10.*"
pytest = ">=8.4.1,<9"
pytest-cov = ">=6.2.1,<7"

[build-dependencies]
setuptools = "==80.9.0"
ninja = "*"
cmake = "*"
packaging = "*"


[feature.common]

[feature.common.pypi-dependencies]
lightning = "*"
torchmetrics = "*"
pre-commit = "*"
optuna = "*"
hydra-core = "*"
hydra-optuna-sweeper = "*"
hydra-submitit-launcher = "*"
colorlog = "*"
hydra-colorlog = "*"
deepspeed = ">=0.17.1"
transformers = "*"
accelerate = ">=1.7.0"
triton = "*"
trl = "*"
omegaconf = "*"
wandb = "*"
rdkit = "*"
jupyterlab = "*"
ipywidgets = "*"
rootutils = "*"
textdistance = "*"
sentencepiece = "*"
dvc = "*"
datasets = "*"
safe-mol = "*"
rouge_score = "*"
evaluate = "*"
nltk = "*"
rich = "*"
nvidia-ml-py = "*"
matplotlib = "*"
seaborn = "*"
cmasher = "*"
tueplots = "*"
matplotx = { version = "*", extras = ["all"] }
distinctipy = "*"


[feature.torch-env]
channels = ["conda-forge", "pytorch", "anaconda"]

[feature.torch-env.pypi-options]
no-build-isolation = true
extra-index-urls = ["https://download.pytorch.org/whl/cu126"]
index-strategy = "unsafe-best-match"

[feature.torch-env.pypi-dependencies]
torch = "==2.8.0"
torchvision = "==0.23.0"
torchaudio = "==2.8.0"
vllm = ">=0.10.2"
flashinfer-python = "*"


[feature.second-env]
channels = ["conda-forge", "pytorch", "anaconda"]

[feature.second-env.dependencies]
python-graphviz = "*"
faiss-gpu = "*"

[feature.second-env.pypi-options]
find-links = [{ url = "https://data.dgl.ai/wheels/torch-2.4/cu124/repo.html" }]
no-build-isolation = true
extra-index-urls = ["https://download.pytorch.org/whl/cu124"]
index-strategy = "unsafe-best-match"

[feature.second-env.pypi-dependencies]
torch = "==2.4.0"
torchvision = "==0.19.0"
torchaudio = "==2.4.0"
torchdata = "<=0.9.0"
syntheseus = { version = "*", extras = ["root-aligned", "graph2edits", "local-retro", "retro-knn", "mhn-react"] }
syntheseus-paroutes = { git = "https://github.com/AustinT/syntheseus-paroutes.git" }
dgl = "*"
xgboost = "==1.0.2"
pymupdf = "*"
route-distances = ">=1.2.4"
openai = "*"
langchain = "*"
langchain-openai = "*"
langchain-community = "*"
langgraph = "*"
rdchiral = "*"
localmapper = "*"
ord-schema = "*"


[environments]
default = { features = ["common", "torch-env"], solve-group = "torch" }
retro = { features = ["common", "second-env"], solve-group = "second" }
