_target_: src.models.cifar_module.CIFARLitModule

net:
  _target_: src.models.components.mobilenetv2.mobilenetv2_cifar
  num_classes: 10
  width_mult: 1.0
  dropout: 0.2
  stride_relax: 3

num_classes: 10
label_smoothing: 0.1

# use optimizer and scheduler defined in configs/optimizer and configs/scheduler
optimizer: ${optimizer}
scheduler: ${scheduler}
# compile model for faster training with pytorch 2.0
compile: false
